version: "{build}"

platform: x64

clone_folder: c:\GOPATH\src\github.com\NebulousLabs\Sia

shallow_clone: true

environment:
  GOPATH: c:\GOPATH

branches:
  only:
    - master
    - staging

install:
  - set PATH=%GOPATH%\bin;%PATH%
  - go version
  - go env
  - go get -d ./...
  - go get github.com/alecthomas/gometalinter

build_script:
  - gometalinter --install
  - gometalinter --disable-all -E gofmt ./...
  - go test -tags="testing debug" -short ./...
  - go test -tags="testing debug" -v -timeout=1200s -race ./...
  - go test -tags="testing debug" -v -run=XXX -bench=. ./...
