
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/NebulousLabs/bolt"
  #version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/NebulousLabs/demotemutex"

[[constraint]]
  branch = "master"
  name = "github.com/NebulousLabs/entropy-mnemonics"

[[constraint]]
  branch = "master"
  name = "github.com/NebulousLabs/errors"

[[constraint]]
  branch = "master"
  name = "github.com/NebulousLabs/fastrand"

[[constraint]]
  branch = "master"
  name = "github.com/NebulousLabs/go-upnp"

[[constraint]]
  branch = "master"
  name = "github.com/NebulousLabs/merkletree"

[[constraint]]
  branch = "master"
  name = "github.com/NebulousLabs/muxado"

[[constraint]]
  name = "github.com/bgentry/speakeasy"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/inconshreveable/go-update"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  name = "github.com/klauspost/reedsolomon"
  version = "1.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/xtaci/smux"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
