// Code generated by "stringer -type=storageObligationStatus"; DO NOT EDIT.

package host

import "strconv"

const _storageObligationStatus_name = "obligationUnresolvedobligationRejectedobligationSucceededobligationFailed"

var _storageObligationStatus_index = [...]uint8{0, 20, 38, 57, 73}

func (i storageObligationStatus) String() string {
	if i >= storageObligationStatus(len(_storageObligationStatus_index)-1) {
		return "storageObligationStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _storageObligationStatus_name[_storageObligationStatus_index[i]:_storageObligationStatus_index[i+1]]
}
